services:
    statts_system_fact:
        class: Statts\Bundle\CommonBundle\Services\StattsSystemFacts
    statts_data_service:
        class: Statts\Bundle\CommonBundle\Services\StattsDataService
        arguments: [@doctrine, @aequasi_cache.redis]
